#ifndef __DRV_SENSOR_DC3V_N20_H__
#define __DRV_SENSOR_DC3V_N20_H__

#define SENSOR_MOTOR_SET_SPEED      (JEE_SENSOR_CTRL_USER_CMD_START + 1)
#define SENSOR_MOTOR_SET_DIRECTION  (JEE_SENSOR_CTRL_USER_CMD_START + 2)
#define SENSOR_MOTOR_SET_ONOFF      (JEE_SENSOR_CTRL_USER_CMD_START + 3)



#endif
